# https://www.playframework.com/documentation/latest/Configuration
play.server.http.address = "0.0.0.0"
play.server.http.port = 9000

play.filters.enabled += "play.filters.cors.CORSFilter"

slick.dbs.default.profile="slick.jdbc.MySQLProfile$"
slick.dbs.default.db.driver="com.mysql.cj.jdbc.Driver"
slick.dbs.default.db.url="jdbc:mysql://azuremysql8823.mysql.database.azure.com:3306/ritik"
slick.dbs.default.db.user="mysqladmin"
slick.dbs.default.db.password="abc"
play.evolutions.db.default.autoApply=true

play.filters.cors {
  pathPrefixes = ["/people"]
  allowedOrigins = ["*"]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE"]
  allowedHttpHeaders = ["Accept", "Origin", "Content-type", "X-Auth-Token"]
  preflightMaxAge = 3 days
}

cassandra {
  contact-points
    {
      host = "cassandra.us-east-1.amazonaws.com"
      port = 9142
    }

  username = "abc"
  password = "abc"
  keyspace = "ecommerce_ks"
}
fs.s3a.path.style.access = true
fs.s3a.connection.ssl.enabled = true

#play.modules.enabled += "modules.SparkModule"
